spring.application.name=HN-KS24-CNTT1-IT211-TranHuuNhat-Project

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/badminton_system_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Huunhat@200506
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=YourSuperSecretKeyForJwtGenerationNeedsToBeAtLeast256BitsLong
app.jwt.expiration-ms=3600000

app.cloudinary.cloud-name=dn9e9omxn
app.cloudinary.api-key=748372592968233
app.cloudinary.api-secret=ws6jPnQyt4F01Tmr9Ui7ILXd1vU

spring.data.redis.host=localhost
spring.data.redis.port=6379